color0 #11131c
color1 #ffb4ab
color2 #64d3ff
color3 #8ad0ef
color4 #b9c3ff
color5 #64d3ff
color6 #8ad0ef
color7 #e2e1ef
color8 #8d8fa6
color9 #ffb4ab
color10 #64d3ff
color11 #8ad0ef
color12 #b9c3ff
color13 #64d3ff
color14 #8ad0ef
color15 #e2e1ef

cursor                #e2e1ef
cursor_text_color     #11131c
background            #11131c
foreground            #e2e1ef
selection_foreground  #c3c5dd
selection_background  #434659
active_border_color   #64d3ff
inactive_border_color #434659
url_color             #64d3ff

active_tab_foreground   #003545
active_tab_background   #64d3ff
inactive_tab_foreground #c3c5dd
inactive_tab_background #434659
cursor_trail_color      #c3c5dd
